image: cypress/browsers:node14.16.0-chrome89-ff86

pipelines:
  default:
    - step:
        name: Install dependencies
        script:
          - npm install

    - step:
        name: Run Cypress tests
        script:
          - npx cypress run
