image: node:latest

pipelines:
  default:
    - step:
        script:
          # install dependencies
          - npm install
          # start the server in the background
          - npm run start &
          # run Cypress tests
          - npx cypress run
