name: Cypress CI

on:
  push:
    branches:
      - main  # Adjust the branch name as per your needs
  pull_request:
    branches:
      - main  # Adjust the branch name as per your needs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Adjust the Node.js version as per your needs

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests
      run: npx cypress run
